### ISSUE TITLE
about pascalcontext ckpt

### ISSUE THREAD

**Issue by mmm-cc** [EnVision-Research/MTMamba#1]
Thanks for your amazing work！ And would you upload the best ckpt of pascal-context，because i found that the ckpt of pascal offered in USAGE  can not reach the result in the pape. I got Infer test restuls:
{'semseg': {'mIoU': 0.7958568505302104}, 'human_parts': {'mIoU': 0.6961288250049167}, 'sal': {'maxF': 0.8344470858573914}, 'normals': {'mean': 17.716591967917022}, 'edge': {'loss': 0.04244312473015932}} and the ckpt of nuydv2 is same as the result in paper.

**Comment by Baijiong-Lin** [comment]
I have tested it again. The inference result of the ckpt I uploaded is right. What is your running environment?

**Comment by mmm-cc** [comment]
> I have tested it again. The inference result of the ckpt I uploaded is right. What is your running environment?

The environment is same as in Requirements, and the NYUD-v2 is ok. maybe i make something wrong, and i will try it again. Thanks a lot.
