### ISSUE TITLE
About FLOPs

### ISSUE THREAD

**Issue by mmm-cc** [EnVision-Research/MTMamba#2]
Thank you for your excellent work! Could you please elaborate on how you computed the FLOPs in your paper?
![image](https://github.com/user-attachments/assets/0ff4a093-f292-40ff-b47e-dab34921518c)
When I calculated it with batch size 1 by 'from thop import profile', I got:
![image](https://github.com/user-attachments/assets/f620c268-aa11-4206-9ade-3b3ee8912202)

**Comment by mmm-cc** [comment]
It appears that the select-scan operation may not have been accounted for in this calculation. Did you handle the complexity of the select operation separately and then incorporate it into the total? like this? 
https://github.com/state-spaces/mamba/issues/110

**Comment by Baijiong-Lin** [comment]
Yes. The complexity of the select-scan operation should be considered separately and added to the total.

**Comment by mmm-cc** [comment]
> Yes. The complexity of the select-scan operation should be considered separately and added to the total.

ok, Thank you!
