### ISSUE TITLE
GPU 

### ISSUE THREAD

**Issue by yanzq95** [EnVision-Research/MTMamba#3]
Excellent work! I want to know if 3090/4090 gpus (24G) can be used to train the MTMamba++. What is the maximum of the batchsize for each 3090/4090 GPU can be set?

**Comment by Baijiong-Lin** [comment]
Yes, MTMamba++ can be trained on 24GB GPUs. The batch size for each GPU is set to 1.

**Comment by yanzq95** [comment]
thks~
